### ISSUE TITLE
addTodo reducer not called

### ISSUE THREAD

**Issue by agiguere** [reduxjs/rtk-convert-todos-example#6]
in todosSlice the addTodo reducer is not call, however the prepare method function is

alex

**Comment by markerikson** [comment]
Are you actually _dispatching_ the action?  Can you show your code?

**Comment by agiguere** [comment]
I have the same code as in 
https://github.com/reduxjs/rtk-convert-todos-example/blob/master/src/features/todos/AddTodo.js

the addTodo is pass in mapDispatch

it looks like to works because I have put a console log in the reducer slice prepare function, the problem is the reducer it self, is not called after

**Comment by agiguere** [comment]
ok got it, I forgot to destruct it in the arrow function component at line 7

thanks
