### ISSUE TITLE
Recommended use of hooks?

### ISSUE THREAD

**Issue by SebastienTainon** [reduxjs/rtk-convert-todos-example#7]
Hello,
Reading the [Redux Style Guide](https://redux.js.org/style-guide/style-guide), I see that it's "strongly recommended" to use React-Redux Hooks: 

> Prefer using the React-Redux hooks API (useSelector and useDispatch) as the default way to interact with a Redux store from your React components. While the classic connect API still works fine and will continue to be supported, the hooks API is generally easier to use in several ways. The hooks have less indirection, less code to write, and are simpler to use with TypeScript than connect is.

However, this project doesn't. For a newcomer in the Redux Toolkit environment like me, do you think this example project is still a good example to learn Redux Toolkit best practices? Or do you recommend another project that "complies" better with Redux Style Guide? And if so, would it be good to update this project to the new standards? Thanks!

**Comment by phryneas** [comment]
Above you link to the Redux style guide. We recommend hooks for **every Redux application**, no matter if they use RTK or not.

At the time this example was created, most applications were still class-based and thus using `connect`. So `connect` was chosen for the "original application" to migrate away from.


Yet, the scope of this project is to show migration from a non-RTK-Codebase to a RTK-Codebase. 

Doing a migration from non-hooks to hooks is simply not in the scope of what the example wants to show.

If you want to see how we recommend to write a new application, you can try `npx create-react-app --template redux` or `npx create-react-app --template redux-typescript`

**Comment by SebastienTainon** [comment]
Thanks for your quick answer. This is indeed a good boilerplate but probably too small to be very useful (simply a counter component). However I've just found [this project](https://github.com/reduxjs/rtk-github-issues-example) which seems to be a more detailed codebase using RTK and also using Redux hooks. It seems to be easier to go deeper into RTK with this one.
